version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data dataset
    tables:
      - name: products
        identifier: raw_gz_product
        description: raw product table

      - name: sales
        identifier: raw_gz_sales
        description: raw sales table

      - name: ship
        identifier: raw_gz_ship
        description: raw shipment table
