version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: products
        identifier: raw_gz_product
        description: raw product table
        columns:
          - name: products_id
            description: id of each product
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: price associated with product

      - name: sales
        freshness:
          warn_after: { count: 90, period: day }
        loaded_at_field: "CAST date_date AS TIMESTAMP"

        identifier: raw_gz_sales
        description: sales of greenweeez/we have one row per product_id found in each orders_id
        tests:
          - unique:
              column_name: "(orders_id|| '-' ||pdt_id)"
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: the id for the order / foreign key to ship
          - name: products_id
            description: the product id associated with the order / foreign key to products
          - name: revenue
            description: revenue generated by the order
          - name: quantity
            description: quantity of the product sold

      - name: ship
        identifier: raw_gz_ship
        description: raw shipment table
        columns:
          - name: orders_id
            description: the id for the order
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping fee associated with the order
          - name: logcost
            description: logistics cost associated with the order
          - name: ship_cost
            description: shipping cost associated with the order


      - name: adwords
        identifier: raw_gz_adwords
        description: Adwords campaigns
        tests:
          - unique:
              column_name: "(date_date|| '-' ||campaign_name)"
          - not_null:
              column_name:
                - date_date
                - paid_source
                - campaign_key
                - campaign_name
                - ads_cost
                - impression
                - click


      
      - name: bing
        identifier: raw_gz_bing
        description: Bing campaigns
        tests:
          - unique:
              column_name: "(date_date|| '-' ||campaign_name)"
          - not_null:
              column_name:
                - date_date
                - paid_source
                - campaign_key
                - campaign_name
                - ads_cost
                - impression
                - click

      - name: criteo
        identifier: raw_gz_criteo
        description: Criteo campaigns
        tests:
          - unique:
              column_name: "(date_date|| '-' ||campaign_name)"
          - not_null:
              column_name:
                - date_date
                - paid_source
                - campaign_key
                - campaign_name
                - ads_cost
                - impression
                - click
      - name: facebook
        identifier: raw_gz_facebook
        description: Facebook campaigns
        tests:
          - unique:
              column_name: "(date_date|| '-' ||campaign_name)"
          - not_null:
              column_name:
                - date_date
                - paid_source
                - campaign_key
                - campaign_name
                - ads_cost
                - impression
                - click
 
            
models:
  - name: int_sales_margin
    description: the margin per product in each order is calculated
    tests:
      - unique:
          column_name: "(orders_id|| '-' ||products_id)"
      - not_null:
          column_name:
            - orders_id
            - products_id
            - margin
            - purchase_cost
            - date_date
            - revenue
            - quantity

  - name: int_orders_margin
    description: the margin orders_id is calculated
    tests:
      - unique:
          column_name: orders_id
      - not_null:
          column_name:
            - orders_id
            - date_date
            - revenue
            - quantity
            - purchase_cost
            - margin

  - name: int_orders_operational
    description: operational margin per orders_id is calcualted
    tests:
      - unique:
          column_name: orders_id
      - not_null:
          column_name:
            - orders_id
            - date_date
            - operational_margin
            - quantity
            - revenue
            - purchase_cost
            - margin
            - shipping_fee
            - logcost
            - ship_cost
          
  - name: int_campaigns
    description: Unioning all campaigns from adwords, bing, criteo, and facebook
    tests:
      - unique:
          column_name: date_date
      - not_null:
          column_name:
            - orders_id
            - products_id
            - margin
            - purchase_cost
            - date_date
            - revenue
            - quantity

  - name: int_campaigns_day
    description: Campaigns data aggregated for date_date (daily)
    tests:
      - unique:
          column_name: date_date
      - not_null:
          column_name:
            - date_date
            - ads_cost

  - name: finance_campaigns_day
    description: Daily finance and ad campaign metrics
    tests:
      - unique:
          column_name: date_date
      - not_null:
          column_name:
            - date_date
            - ads_margin
            - average_basket
            - operational_margin